fix: Fix build error due to libpng linker configuration fault
This patch should fix the following build error:

```
libtool: link: g++ -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gegl-0.4 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/babl-0.1 -O2 -pipe -march=native -o iscan iscan-file-selector.o iscan-pisa_aleart_dialog.o iscan-pisa_change_unit.o iscan-pisa_configuration.o iscan-pisa_error.o iscan-pisa_gamma_correction.o iscan-pisa_gimp.o iscan-pisa_image_controls.o iscan-pisa_img_converter.o iscan-pisa_main.o iscan-pisa_main_window.o iscan-pisa_marquee.o iscan-pisa_preference.o iscan-pisa_preview_window.o iscan-pisa_progress_window.o iscan-pisa_sane_scan.o iscan-pisa_scan_manager.o iscan-pisa_scan_selector.o iscan-pisa_scan_tool.o iscan-pisa_settings.o iscan-pisa_tool.o iscan-pisa_view_manager.o iscan-xpm_data.o ../non-free/libesmod.so  -lpng16 ../lib/.libs/libimage-stream.a -lltdl -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lsane -pthread
/usr/bin/ld: ../lib/.libs/libimage-stream.a(libimage_stream_la-pngstream.o): undefined reference to symbol 'png_set_longjmp_fn@@PNG16_0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libpng16.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Authored-by: Unknown
Sourced-from: Recipes/03-iscan-2.29.1-png-libs.patch at master · gobolinux/Recipes <https://github.com/gobolinux/Recipes/blob/master/IScan/2.30.1/03-iscan-2.29.1-png-libs.patch>
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>